// ==UserScript==
// @name        Stack Exchange, OpenAI detector
// @namespace   https://github.com/Glorfindel83/
// @description Adds a button to check the probability that a post was written by a bot
// @author      Glorfindel
// @updateURL   https://raw.githubusercontent.com/Glorfindel83/SE-Userscripts/master/openai-detector/openai-detector.user.js
// @downloadURL https://raw.githubusercontent.com/Glorfindel83/SE-Userscripts/master/openai-detector/openai-detector.user.js
// @supportURL  https://stackapps.com/questions/9611/openai-detector
// @version     0.2
// @match       *://*.stackexchange.com/questions/*
// @match       *://*.stackoverflow.com/questions/*
// @match       *://*.superuser.com/questions/*
// @match       *://*.serverfault.com/questions/*
// @match       *://*.askubuntu.com/questions/*
// @match       *://*.stackapps.com/questions/*
// @match       *://*.mathoverflow.net/questions/*
// @exclude     *://*.stackexchange.com/questions/ask
// @exclude     *://*.stackoverflow.com/questions/ask
// @exclude     *://*.superuser.com/questions/ask
// @exclude     *://*.serverfault.com/questions/ask
// @exclude     *://*.askubuntu.com/questions/ask
// @exclude     *://*.stackapps.com/questions/ask
// @exclude     *://*.mathoverflow.net/questions/ask
// @connect     huggingface.co
// @require     https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @grant       GM_xmlhttpRequest
// @grant       GM.xmlHttpRequest
// ==/UserScript==

(function () {
  "use strict";

  $("a.js-share-link").each(function() {
    let shareButton = $(this);

    // Add button
    let button = $('<button class="s-btn s-btn__link" type="button" href="#">Detect OpenAI</button>');
    let cell = $('<div class="flex--item"></div>');
    cell.append(button);
    let menu = shareButton.parent().parent();
    menu.append(cell);

    function detectAI(event) {
      let post = shareButton.parents(".answercell");
      if (post.length == 0) {
        post = shareButton.parents(".postcell");
      }
      let text = post.find(".js-post-body").text().trim();
      $.ajaxSetup({ cache: true });
      $.get("https://huggingface.co/openai-detector?" + encodeURIComponent(text), function (data) {
        let message = "According to Hugging Face, the chance that this post was generated by OpenAI is "
          + Math.round(data.fake_probability * 100, 2) + "%.";
        $("body").append($(`
<div class="s-toast js-toast js-stacks-managed-popup js-fades-with-aria-hidden" aria-hidden="false" style="top: 60px;">
  <aside class="s-notice s-notice__info" role="status" aria-live="polite">
    <div class="d-flex gs16 gsx ai-center jc-space-between">
      <div class="flex--item">
        <div class="m0 js-toast-body" id="notice-toast-message">` + message + `</div>
      </div>
      <div class="flex--item mr0 js-notice-actions">
        <div class="d-flex">
          <button class="p8 s-btn d-flex flex__center fc-dark js-dismiss" tabindex="0" role="button" aria-label="Dismiss">
            <svg class="m0 svg-icon iconClearSm" aria-hidden="true" width="14" height="14" viewBox="0 0 14 14">
              <path d="M12 3.41 10.59 2 7 5.59 3.41 2 2 3.41 5.59 7 2 10.59 3.41 12 7 8.41 10.59 12 12 10.59 8.41 7 12 3.41Z"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </aside>
</div>`));
      });
    }
    button.on('click', detectAI);
  });
})();
